<a href="https://colab.research.google.com/github/guptamanishacs/E2Recycle/blob/main/T080_PRAC_3_A%2CB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import zipfile

zip_path = "Plant_1_Generation_Data.csv (1).zip"

with zipfile.ZipFile(zip_path, 'r') as z:
    z.extractall()



In [9]:
import pandas as pd

data = pd.read_csv("Plant_1_Generation_Data.csv")
data.head()


DATE_TIME  PLANT_ID       SOURCE_KEY  DC_POWER  AC_POWER  \
0  15-05-2020 00:00   4135001  1BY6WEcLGh8j5v7       0.0       0.0   
1  15-05-2020 00:00   4135001  1IF53ai7Xc0U56Y       0.0       0.0   
2  15-05-2020 00:00   4135001  3PZuoBAID5Wc2HD       0.0       0.0   
3  15-05-2020 00:00   4135001  7JYdWkrLSPkdwr4       0.0       0.0   
4  15-05-2020 00:00   4135001  McdE0feGgRqW7Ca       0.0       0.0   

   DAILY_YIELD  TOTAL_YIELD  
0          0.0    6259559.0  
1          0.0    6183645.0  
2          0.0    6987759.0  
3          0.0    7602960.0  
4          0.0    7158964.0

In [14]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Load your dataset
df = pd.read_csv("Plant_1_Generation_Data.csv")

# Show all columns
print("Columns in dataset:\n", df.columns)

# Select any numerical column for scaling
# Example: DC_POWER --- change column here as per your requirement
column = "DC_POWER"

# Extract the feature and reshape
feature = df[[column]].values   # 2D array for scaler

print("\nOriginal Data Sample (first 10 values):")
print(feature[:10])

# Create MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Fit and transform
scaled_feature = scaler.fit_transform(feature)

print("\nScaled Data Sample (first 10 values):")
print(scaled_feature[:10])

# Show min and max values used for scaling
print("\nMinimum value in column:", scaler.data_min_)
print("Maximum value in column:", scaler.data_max_)


Columns in dataset:
 Index(['DATE_TIME', 'PLANT_ID', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER',
       'DAILY_YIELD', 'TOTAL_YIELD'],
      dtype='object')

Original Data Sample (first 10 values):
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Scaled Data Sample (first 10 values):
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Minimum value in column: [0.]
Maximum value in column: [14471.125]


In [16]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, RobustScaler

# Load file uploaded in Colab
df = pd.read_csv("Plant_1_Generation_Data.csv")   # change if name is different

print("Numeric columns:")
print(df.select_dtypes(include=['float64', 'int64']).columns)

# Select the column to scale
column = "DC_POWER"

feature = df[[column]].values

print("\nOriginal Feature (first 10 values):")
print(feature[:10])

# Standard Scaler
scaler = StandardScaler()
standardized = scaler.fit_transform(feature)

print("\nStandardized Values (first 10):")
print(standardized[:10])

print("\nMean:", round(standardized.mean(), 4))
print("Std Dev:", round(standardized.std(), 4))

# Robust Scaler
robust_scaler = RobustScaler()
robust_scaled = robust_scaler.fit_transform(feature)

print("\nRobust Scaled Values (first 10):")
print(robust_scaled[:10])


Numeric columns:
Index(['PLANT_ID', 'DC_POWER', 'AC_POWER', 'DAILY_YIELD', 'TOTAL_YIELD'], dtype='object')

Original Feature (first 10 values):
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Standardized Values (first 10):
[[-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]
 [-0.77975535]]

Mean: 0.0
Std Dev: 1.0

Robust Scaled Values (first 10):
[[-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]
 [-0.06737905]]


In [17]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Normalizer

# ---------------------------------------------
# STEP 1 — Load Uploaded Dataset
# ---------------------------------------------
df = pd.read_csv("Plant_1_Generation_Data.csv")   # use exact uploaded filename

# Select 2 numeric columns for normalization, ensuring non-zero values for demonstration
# Filter for rows where at least one of the power values is greater than 0
features = df[(df["DC_POWER"] > 0) | (df["AC_POWER"] > 0)][["DC_POWER", "AC_POWER"]].head(5).values

# If no non-zero values are found in the head(5), try a larger sample or fall back to original head(5)
if features.shape[0] == 0:
    print("Warning: No non-zero power values found in the first few rows. Using original head(5).")
    features = df[["DC_POWER", "AC_POWER"]].head(5).values

print("Original Feature Matrix (first 5 rows with non-zero power):")
print(features)

# ---------------------------------------------
# STEP 2 — L2 Normalization (unit length = 1)
# ---------------------------------------------
normalizer_l2 = Normalizer(norm="l2")
features_l2_norm = normalizer_l2.transform(features)

print("\nL2 Normalized Matrix:")
print(features_l2_norm)

# ---------------------------------------------
# STEP 3 — L1 Normalization (sum of row = 1)
# ---------------------------------------------
normalizer_l1 = Normalizer(norm="l1")
features_l1_norm = normalizer_l1.transform(features)

print("\nL1 Normalized Matrix:")
print(features_l1_norm)

# Confirm L1 normalization (only for rows that are not all zeros)
if features_l1_norm.shape[0] > 0 and not np.all(features_l1_norm[0] == 0):
    print("\nSum of first row (should be 1):")
    print(features_l1_norm[0,0] + features_l1_norm[0,1])
else:
    print("\nCannot confirm L1 sum to 1 as the selected features are all zeros.")

Original Feature Matrix (first 5 rows):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

L2 Normalized Matrix:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

L1 Normalized Matrix:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Sum of first row (should be 1): 0.0


In [18]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("Plant_1_Generation_Data.csv")   # use exact uploaded filename

# Select the first 1000 rows (or more, if needed) to ensure data variation
features = df[["DC_POWER", "AC_POWER"]].dropna().head(1000)

print("Selected Features (first 5 rows):")
print(features.head())

# Convert to array
X = features.values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize KMeans with 3 clusters
clusterer = KMeans(n_clusters=3, random_state=0, n_init='auto') # Added n_init='auto' to suppress future warning

# Fit
clusterer.fit(X_scaled)

# Predict cluster group
features["group"] = clusterer.predict(X_scaled)

# ---------------------------------------------
# STEP 5 — Show final output
# ---------------------------------------------
print("\nFinal Clustered Output:")
print(features.head())

Selected Features (first 5 rows):
   DC_POWER  AC_POWER
0       0.0       0.0
1       0.0       0.0
2       0.0       0.0
3       0.0       0.0
4       0.0       0.0

Final Clustered Output:
   DC_POWER  AC_POWER  group
0       0.0       0.0      0
1       0.0       0.0      0
2       0.0       0.0      0
3       0.0       0.0      0
4       0.0       0.0      0


/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: ConvergenceWarning: Number of distinct clusters (1) found smaller than n_clusters (3). Possibly due to duplicate points in X.
  return fit_method(estimator, *args, **kwargs)


In [19]:
import pandas as pd
import numpy as np

df = pd.read_csv("Plant_1_Generation_Data.csv")   # use exact uploaded file name

# Show first 5 rows
print("Original Data (first 5 rows):")
print(df[["DC_POWER", "AC_POWER"]].head())


features = df[["DC_POWER", "AC_POWER"]].values

print("\nFeature Matrix (with missing values if any):")
print(features[:10])   # show first 10 rows

cleaned_features = features[~np.isnan(features).any(axis=1)]

print("\nAfter Removing Missing Values (NumPy method):")
print(cleaned_features[:10])   # first 10 rows

# STEP 4 — Using pandas DataFrame dropna() (same format)
df_cleaned = df[["DC_POWER", "AC_POWER"]].dropna()

print("\nDataFrame After dropna():")
print(df_cleaned.head())


Original Data (first 5 rows):
   DC_POWER  AC_POWER
0       0.0       0.0
1       0.0       0.0
2       0.0       0.0
3       0.0       0.0
4       0.0       0.0

Feature Matrix (with missing values if any):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

After Removing Missing Values (NumPy method):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

DataFrame After dropna():
   DC_POWER  AC_POWER
0       0.0       0.0
1       0.0       0.0
2       0.0       0.0
3       0.0       0.0
4       0.0       0.0


In [24]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# STEP 1 — Load Dataset
df = pd.read_csv("Plant_1_Generation_Data.csv")   # use exact uploaded filename

features = df[["DC_POWER", "AC_POWER"]].dropna().head(1000).values

print("Original Features (first 5 rows):")
print(features[:5])

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

# Store true value BEFORE inserting NaN
true_value = standardized_features[0, 0]

# Intentionally introduce a NaN for demonstration purposes
standardized_features[0, 0] = np.nan

print("\nTrue Value before missing:", true_value)

# Show the column mean with the introduced NaN, for clarity
print("Mean of column 0 with NaN (before imputation):", np.nanmean(standardized_features[:, 0]))

# STEP 3 — Create Imputer (Mean Strategy)
mean_imputer = SimpleImputer(strategy="mean")

# Impute missing values
features_mean_imputed = mean_imputer.fit_transform(standardized_features)

# STEP 4 — Show results
print("\nImputed Value:", features_mean_imputed[0, 0])

Original Features (first 5 rows):
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

True Value before missing: -0.7251745652614473
Mean of column 0 with NaN (before imputation): 0.0007259004657270679

Imputed Value: 0.0007259004657270679


In [21]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelBinarizer

df = pd.read_csv("/content/Plant_1_Generation_Data.csv")

feature = df["SOURCE_KEY"].values.reshape(-1, 1)

one_hot = LabelBinarizer()
encoded = one_hot.fit_transform(feature)

print(encoded[:10])
print(one_hot.classes_)

decoded = one_hot.inverse_transform(encoded[:10])
print(decoded)

dummy_df = pd.get_dummies(df["SOURCE_KEY"])
print(dummy_df.head())

encoded_df = pd.concat([df, dummy_df], axis=1)
print(encoded_df.head())


[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]
['1BY6WEcLGh8j5v7' '1IF53ai7Xc0U56Y' '3PZuoBAID5Wc2HD' '7JYdWkrLSPkdwr4'
 'McdE0feGgRqW7Ca' 'VHMLBKoKgIrUVDU' 'WRmjgnKYAwPKWDb' 'YxYtjZvoooNbGkE'
 'ZnxXDlPa8U1GXgE' 'ZoEaEvLYb1n2sOq' 'adLQvlD726eNBSB' 'bvBOhCH3iADSZry'
 'iCRJl6heRkivqQ3' 'ih0vzX44oOqAx2f' 'pkci93gMrogZuBj' 'rGa61gmuvPhdLxV'
 'sjndEbLyjtCKgGv' 'uHbuxQJl8lW7ozc' 'wCURE6d3bPkepu2' 'z9Y9gH1T5YWrNuG'
 'zBIq5rxdHJRwDNY' 'zVJPv84UY57bAof']
['1BY6WEcLGh8j5v7' '1IF53ai7Xc0U56Y' '3PZuoBAID5Wc2HD' '7JYdWkrLSPkdwr4'
 'McdE0feGgRqW7Ca' 'VHMLBKoKgIrUVDU' 'WRmjgnKYAwPKWDb

In [25]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction import DictVectorizer
from sklearn.impute import SimpleImputer

df = pd.read_csv("/content/Plant_1_Generation_Data.csv")

df["DC_CATEGORY"] = pd.cut(df["DC_POWER"],
                           bins=[-1, 500, 2000, 7000],
                           labels=["Low", "Medium", "High"])

df["DC_CATEGORY"] = df["DC_CATEGORY"].astype(str)
scale_mapper = {"Low": 1, "Medium": 2, "High": 3}
ordinal_encoded = df["DC_CATEGORY"].map(scale_mapper)
print(ordinal_encoded.head())

dict_data = df[["DC_POWER", "AC_POWER"]].head(4).to_dict(orient="records")
vec = DictVectorizer(sparse=False)
dict_encoded = vec.fit_transform(dict_data)
print(dict_encoded)
print(vec.get_feature_names_out())

df_missing = df[["AC_POWER", "DC_POWER"]].copy()
df_missing.loc[0, "AC_POWER"] = np.nan

imp = SimpleImputer(strategy="mean")
df_filled = imp.fit_transform(df_missing)

print(df_filled[:5])


0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: DC_CATEGORY, dtype: float64
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
['AC_POWER' 'DC_POWER']
[[307.80722764   0.        ]
 [  0.           0.        ]
 [  0.           0.        ]
 [  0.           0.        ]
 [  0.           0.        ]]


In [28]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

df = pd.read_csv("Plant_1_Generation_Data.csv")

features = df[["DC_POWER", "AC_POWER"]].values

scaler = StandardScaler()
standardized_features = scaler.fit_transform(features)

true_value = standardized_features[0, 0]
standardized_features[0, 0] = np.nan

mean_imputer = SimpleImputer(strategy="mean")
features_mean_imputed = mean_imputer.fit_transform(standardized_features)

print("True Value: {}".format(true_value))
print("Imputed Value: {}".format(features_mean_imputed[0, 0]))


True Value: -0.7797553549828352
Imputed Value: 1.1337443549317069e-05
